import '../entities/biomarker.dart';

/// Health data returned from Health Connect/HealthKit
class HealthData {
  final int? sleepDuration; // minutes
  final double? hrv; // milliseconds (SDNN)
  final int? rhr; // beats per minute

  const HealthData({
    this.sleepDuration,
    this.hrv,
    this.rhr,
  });

  /// Convert HealthData to Biomarker entity
  Biomarker toBiomarker(int userId) {
    final now = DateTime.now();
    return Biomarker(
      id: 0, // Will be auto-generated by database
      userId: userId,
      date: DateTime(now.year, now.month, now.day), // Start of day
      sleepDuration: sleepDuration,
      hrv: hrv,
      rhr: rhr,
      createdAt: now,
      updatedAt: now,
    );
  }
}

/// Health service for device integration (Health Connect/HealthKit)
abstract class HealthService {
  /// Request permissions for health data access
  /// Returns true if permissions granted, false otherwise
  Future<bool> requestPermissions();

  /// Check if permissions are granted for health data access
  Future<bool> hasPermissions();

  /// Fetch today's health data (sleep, HRV, RHR)
  /// Returns null if no data available or permissions denied
  Future<HealthData?> fetchTodaysHealthData();

  /// Fetch workouts recorded today from external sources
  Future<List<ExternalWorkout>> fetchTodaysWorkouts();
}

/// Represents a workout synced from Health Connect / HealthKit
class ExternalWorkout {
  final String id;
  final String type; // e.g. "Running", "Cycling"
  final DateTime startTime;
  final DateTime endTime;
  final int durationSeconds;
  final double? distanceKm;
  final int? energryBurnedKcal;
  final String sourceName; // e.g. "Apple Watch", "Garmin"

  const ExternalWorkout({
    required this.id,
    required this.type,
    required this.startTime,
    required this.endTime,
    required this.durationSeconds,
    this.distanceKm,
    this.energryBurnedKcal,
    required this.sourceName,
  });
}
