import 'package:drift/drift.dart';

@DataClassName('WorkoutDTO')
class Workouts extends Table {
  // Use Text for ID to support UUIDs generated by the app/AI
  TextColumn get id => text()();

  // Foreign Keys (assuming mapped from Ints in Users/Goals tables)
  IntColumn get userId => integer()();
  IntColumn get goalId => integer()();

  TextColumn get mesocycleId => text().nullable()();
  TextColumn get microcycleId => text().nullable()();

  DateTimeColumn get scheduledDate => dateTime()();
  TextColumn get type => text()(); // 'easy_run', etc.
  TextColumn get name => text()();
  IntColumn get plannedDuration => integer()(); // seconds
  RealColumn get plannedDistance => real().nullable()(); // km
  TextColumn get intensity => text().nullable()();
  TextColumn get description => text().nullable()();

  // 'planned', 'in_progress', 'completed', 'skipped', 'missed'
  TextColumn get status => text()();

  IntColumn get actualDuration => integer().nullable()();
  RealColumn get actualDistance => real().nullable()();
  RealColumn get actualPace => real().nullable()();
  IntColumn get rpe => integer().nullable()();
  DateTimeColumn get completedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
