import 'package:drift/drift.dart';

@DataClassName('WorkoutDTO')
class Workouts extends Table {
  // Use Text for ID to support UUIDs generated by the app/AI
  TextColumn get id => text()();

  // Foreign Keys (assuming mapped from Ints in Users/Goals tables)
  IntColumn get userId => integer()();
  IntColumn get goalId => integer()();

  TextColumn get phaseId => text().nullable()();
  TextColumn get blockId => text().nullable()();

  DateTimeColumn get scheduledDate => dateTime()();
  TextColumn get type => text()(); // 'easy_run', etc.
  TextColumn get name => text()();
  IntColumn get plannedDuration => integer()(); // seconds
  RealColumn get plannedDistance => real().nullable()(); // km
  IntColumn get intensity => integer().nullable()(); // RPE (1-10)
  TextColumn get description => text().nullable()();

  // 'planned', 'in_progress', 'completed', 'skipped', 'missed'
  TextColumn get status => text()();

  IntColumn get actualDuration => integer().nullable()();
  RealColumn get actualDistance => real().nullable()();
  RealColumn get actualPace => real().nullable()();
  IntColumn get rpe => integer().nullable()();
  TextColumn get syncedFrom =>
      text().nullable()(); // 'manual', 'health_api', 'screenshot'
  DateTimeColumn get completedAt => dateTime().nullable()();

  // Flag for "Big Rocks" (Long Runs, intervals, high-priority strength)
  BoolColumn get isKey => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}
