// Mocks generated by Mockito 5.4.6 from annotations
// in ash_trainer/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ash_trainer/features/shared/domain/entities/goal.dart' as _i3;
import 'package:ash_trainer/features/shared/domain/entities/user.dart' as _i2;
import 'package:ash_trainer/features/shared/domain/repositories/goal_repository.dart'
    as _i6;
import 'package:ash_trainer/features/shared/domain/repositories/user_repository.dart'
    as _i4;
import 'package:ash_trainer/features/training/application/usecases/generate_training_plan.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoal_1 extends _i1.SmartFake implements _i3.Goal {
  _FakeGoal_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> createUser(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #createUser,
            [user],
          ),
        )),
      ) as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i2.User?>.value(),
      ) as _i5.Future<_i2.User?>);

  @override
  _i5.Future<void> updateUser(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAvailableDays(List<String>? days) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAvailableDays,
          [days],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateHealthPermissions(bool? granted) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHealthPermissions,
          [granted],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalRepository extends _i1.Mock implements _i6.GoalRepository {
  MockGoalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Goal> createGoal(_i3.Goal? goal) => (super.noSuchMethod(
        Invocation.method(
          #createGoal,
          [goal],
        ),
        returnValue: _i5.Future<_i3.Goal>.value(_FakeGoal_1(
          this,
          Invocation.method(
            #createGoal,
            [goal],
          ),
        )),
      ) as _i5.Future<_i3.Goal>);

  @override
  _i5.Future<_i3.Goal> getGoal(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getGoal,
          [id],
        ),
        returnValue: _i5.Future<_i3.Goal>.value(_FakeGoal_1(
          this,
          Invocation.method(
            #getGoal,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Goal>);

  @override
  _i5.Future<List<_i3.Goal>> getGoals() => (super.noSuchMethod(
        Invocation.method(
          #getGoals,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Goal>>.value(<_i3.Goal>[]),
      ) as _i5.Future<List<_i3.Goal>>);

  @override
  _i5.Future<_i3.Goal?> getActiveGoal() => (super.noSuchMethod(
        Invocation.method(
          #getActiveGoal,
          [],
        ),
        returnValue: _i5.Future<_i3.Goal?>.value(),
      ) as _i5.Future<_i3.Goal?>);

  @override
  _i5.Future<void> updateGoal(_i3.Goal? goal) => (super.noSuchMethod(
        Invocation.method(
          #updateGoal,
          [goal],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateConfidence({
    required String? goalId,
    required double? confidence,
    required double? adherenceScore,
    required double? qualityScore,
    required double? consistencyScore,
    required double? recoveryScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfidence,
          [],
          {
            #goalId: goalId,
            #confidence: confidence,
            #adherenceScore: adherenceScore,
            #qualityScore: qualityScore,
            #consistencyScore: consistencyScore,
            #recoveryScore: recoveryScore,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deactivateGoal(String? goalId) => (super.noSuchMethod(
        Invocation.method(
          #deactivateGoal,
          [goalId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteGoal(String? goalId) => (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [goalId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GenerateTrainingPlan].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateTrainingPlan extends _i1.Mock
    implements _i7.GenerateTrainingPlan {
  MockGenerateTrainingPlan() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> execute({
    required String? goalId,
    required String? userId,
    DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #goalId: goalId,
            #userId: userId,
            #startDate: startDate,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
